# Generated by Django 5.1.7 on 2025-03-10 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_front_image', models.ImageField(upload_to='images/')),
                ('card_back_image', models.ImageField(upload_to='images/')),
                ('combined_image', models.ImageField(blank=True, null=True, upload_to='combined_images/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('number', models.TextField()),
                ('set', models.TextField()),
                ('card_company', models.TextField()),
                ('numeration', models.TextField()),
                ('autograph', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cardimage')),
            ],
        ),
    ]
