# Generated by Django 5.1.7 on 2025-03-13 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_front_image', models.ImageField(upload_to='images/')),
                ('card_back_image', models.ImageField(upload_to='images/')),
                ('combined_image', models.ImageField(blank=True, null=True, upload_to='combined_images/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('set', models.CharField(max_length=20)),
                ('card_company', models.CharField(max_length=20)),
                ('numeration', models.CharField(blank=True, max_length=20, null=True)),
                ('autograph', models.BooleanField()),
                ('is_graded', models.BooleanField()),
                ('grade_company', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cardimage')),
            ],
        ),
        migrations.CreateModel(
            name='CardShop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
